// Code generated by MockGen. DO NOT EDIT.
// Source: ./vision_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	visionpb "cloud.google.com/go/vision/v2/apiv1/visionpb"
	gomock "github.com/golang/mock/gomock"
	gax "github.com/googleapis/gax-go/v2"
)

// MockVisionClient is a mock of VisionClient interface.
type MockVisionClient struct {
	ctrl     *gomock.Controller
	recorder *MockVisionClientMockRecorder
}

// MockVisionClientMockRecorder is the mock recorder for MockVisionClient.
type MockVisionClientMockRecorder struct {
	mock *MockVisionClient
}

// NewMockVisionClient creates a new mock instance.
func NewMockVisionClient(ctrl *gomock.Controller) *MockVisionClient {
	mock := &MockVisionClient{ctrl: ctrl}
	mock.recorder = &MockVisionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisionClient) EXPECT() *MockVisionClientMockRecorder {
	return m.recorder
}

// BatchAnnotateImages mocks base method.
func (m *MockVisionClient) BatchAnnotateImages(arg0 context.Context, arg1 *visionpb.BatchAnnotateImagesRequest, arg2 ...gax.CallOption) (*visionpb.BatchAnnotateImagesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchAnnotateImages", varargs...)
	ret0, _ := ret[0].(*visionpb.BatchAnnotateImagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchAnnotateImages indicates an expected call of BatchAnnotateImages.
func (mr *MockVisionClientMockRecorder) BatchAnnotateImages(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAnnotateImages", reflect.TypeOf((*MockVisionClient)(nil).BatchAnnotateImages), varargs...)
}

// Close mocks base method.
func (m *MockVisionClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockVisionClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVisionClient)(nil).Close))
}
