// Code generated by MockGen. DO NOT EDIT.
// Source: ./image_analysis_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/pedro00627/image-analyzer-api/internal/application/service"
	entity "github.com/pedro00627/image-analyzer-api/internal/domain/entity"
)

// MockImageAnalysisService is a mock of ImageAnalysisService interface.
type MockImageAnalysisService struct {
	ctrl     *gomock.Controller
	recorder *MockImageAnalysisServiceMockRecorder
}

// MockImageAnalysisServiceMockRecorder is the mock recorder for MockImageAnalysisService.
type MockImageAnalysisServiceMockRecorder struct {
	mock *MockImageAnalysisService
}

// NewMockImageAnalysisService creates a new mock instance.
func NewMockImageAnalysisService(ctrl *gomock.Controller) *MockImageAnalysisService {
	mock := &MockImageAnalysisService{ctrl: ctrl}
	mock.recorder = &MockImageAnalysisServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageAnalysisService) EXPECT() *MockImageAnalysisServiceMockRecorder {
	return m.recorder
}

// AnalyzeImage mocks base method.
func (m *MockImageAnalysisService) AnalyzeImage(ctx context.Context, request *service.AnalyzeImageRequest) (*entity.AnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeImage", ctx, request)
	ret0, _ := ret[0].(*entity.AnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeImage indicates an expected call of AnalyzeImage.
func (mr *MockImageAnalysisServiceMockRecorder) AnalyzeImage(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeImage", reflect.TypeOf((*MockImageAnalysisService)(nil).AnalyzeImage), ctx, request)
}
