// Code generated by MockGen. DO NOT EDIT.
// Source: ./image_validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateContent mocks base method.
func (m *MockValidator) ValidateContent(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContent", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContent indicates an expected call of ValidateContent.
func (mr *MockValidatorMockRecorder) ValidateContent(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContent", reflect.TypeOf((*MockValidator)(nil).ValidateContent), data)
}

// ValidateSize mocks base method.
func (m *MockValidator) ValidateSize(size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSize", size)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSize indicates an expected call of ValidateSize.
func (mr *MockValidatorMockRecorder) ValidateSize(size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSize", reflect.TypeOf((*MockValidator)(nil).ValidateSize), size)
}

// ValidateType mocks base method.
func (m *MockValidator) ValidateType(filename, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateType", filename, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateType indicates an expected call of ValidateType.
func (mr *MockValidatorMockRecorder) ValidateType(filename, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateType", reflect.TypeOf((*MockValidator)(nil).ValidateType), filename, contentType)
}
