// Code generated by MockGen. DO NOT EDIT.
// Source: ./config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetAllowedMimes mocks base method.
func (m *MockConfig) GetAllowedMimes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedMimes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedMimes indicates an expected call of GetAllowedMimes.
func (mr *MockConfigMockRecorder) GetAllowedMimes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedMimes", reflect.TypeOf((*MockConfig)(nil).GetAllowedMimes))
}

// GetMaxSize mocks base method.
func (m *MockConfig) GetMaxSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetMaxSize indicates an expected call of GetMaxSize.
func (mr *MockConfigMockRecorder) GetMaxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxSize", reflect.TypeOf((*MockConfig)(nil).GetMaxSize))
}

// GetProvider mocks base method.
func (m *MockConfig) GetProvider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockConfigMockRecorder) GetProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockConfig)(nil).GetProvider))
}

// GetSecret mocks base method.
func (m *MockConfig) GetSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockConfigMockRecorder) GetSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockConfig)(nil).GetSecret))
}
