// Code generated by MockGen. DO NOT EDIT.
// Source: ./config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetAllowedMimes mocks base method.
func (m *MockConfig) GetAllowedMimes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedMimes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedMimes indicates an expected call of GetAllowedMimes.
func (mr *MockConfigMockRecorder) GetAllowedMimes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedMimes", reflect.TypeOf((*MockConfig)(nil).GetAllowedMimes))
}

// GetAllowedOrigins mocks base method.
func (m *MockConfig) GetAllowedOrigins() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedOrigins")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedOrigins indicates an expected call of GetAllowedOrigins.
func (mr *MockConfigMockRecorder) GetAllowedOrigins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedOrigins", reflect.TypeOf((*MockConfig)(nil).GetAllowedOrigins))
}

// GetMaxSize mocks base method.
func (m *MockConfig) GetMaxSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetMaxSize indicates an expected call of GetMaxSize.
func (mr *MockConfigMockRecorder) GetMaxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxSize", reflect.TypeOf((*MockConfig)(nil).GetMaxSize))
}

// GetProvider mocks base method.
func (m *MockConfig) GetProvider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockConfigMockRecorder) GetProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockConfig)(nil).GetProvider))
}

// GetRateLimitBurst mocks base method.
func (m *MockConfig) GetRateLimitBurst() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimitBurst")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRateLimitBurst indicates an expected call of GetRateLimitBurst.
func (mr *MockConfigMockRecorder) GetRateLimitBurst() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimitBurst", reflect.TypeOf((*MockConfig)(nil).GetRateLimitBurst))
}

// GetRateLimitPerMinute mocks base method.
func (m *MockConfig) GetRateLimitPerMinute() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimitPerMinute")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRateLimitPerMinute indicates an expected call of GetRateLimitPerMinute.
func (mr *MockConfigMockRecorder) GetRateLimitPerMinute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimitPerMinute", reflect.TypeOf((*MockConfig)(nil).GetRateLimitPerMinute))
}

// GetSecret mocks base method.
func (m *MockConfig) GetSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockConfigMockRecorder) GetSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockConfig)(nil).GetSecret))
}

// GetWorkerPoolQueueSize mocks base method.
func (m *MockConfig) GetWorkerPoolQueueSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerPoolQueueSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWorkerPoolQueueSize indicates an expected call of GetWorkerPoolQueueSize.
func (mr *MockConfigMockRecorder) GetWorkerPoolQueueSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerPoolQueueSize", reflect.TypeOf((*MockConfig)(nil).GetWorkerPoolQueueSize))
}

// GetWorkerPoolSize mocks base method.
func (m *MockConfig) GetWorkerPoolSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerPoolSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWorkerPoolSize indicates an expected call of GetWorkerPoolSize.
func (mr *MockConfigMockRecorder) GetWorkerPoolSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerPoolSize", reflect.TypeOf((*MockConfig)(nil).GetWorkerPoolSize))
}
