// Code generated by MockGen. DO NOT EDIT.
// Source: ./analyze_image.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	usecase "github.com/pedro00627/image-analyzer-api/internal/application/usecase"
	entity "github.com/pedro00627/image-analyzer-api/internal/domain/entity"
)

// MockAnalyzeImageUseCaseInterface is a mock of AnalyzeImageUseCaseInterface interface.
type MockAnalyzeImageUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzeImageUseCaseInterfaceMockRecorder
}

// MockAnalyzeImageUseCaseInterfaceMockRecorder is the mock recorder for MockAnalyzeImageUseCaseInterface.
type MockAnalyzeImageUseCaseInterfaceMockRecorder struct {
	mock *MockAnalyzeImageUseCaseInterface
}

// NewMockAnalyzeImageUseCaseInterface creates a new mock instance.
func NewMockAnalyzeImageUseCaseInterface(ctrl *gomock.Controller) *MockAnalyzeImageUseCaseInterface {
	mock := &MockAnalyzeImageUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAnalyzeImageUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzeImageUseCaseInterface) EXPECT() *MockAnalyzeImageUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAnalyzeImageUseCaseInterface) Execute(ctx context.Context, req usecase.AnalyzeImageRequest) (*entity.AnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*entity.AnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAnalyzeImageUseCaseInterfaceMockRecorder) Execute(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAnalyzeImageUseCaseInterface)(nil).Execute), ctx, req)
}
