// Code generated by MockGen. DO NOT EDIT.
// Source: ./ai_analyzer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/pedro00627/image-analyzer-api/internal/domain/entity"
)

// MockAIAnalyzer is a mock of AIAnalyzer interface.
type MockAIAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockAIAnalyzerMockRecorder
}

// MockAIAnalyzerMockRecorder is the mock recorder for MockAIAnalyzer.
type MockAIAnalyzerMockRecorder struct {
	mock *MockAIAnalyzer
}

// NewMockAIAnalyzer creates a new mock instance.
func NewMockAIAnalyzer(ctrl *gomock.Controller) *MockAIAnalyzer {
	mock := &MockAIAnalyzer{ctrl: ctrl}
	mock.recorder = &MockAIAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIAnalyzer) EXPECT() *MockAIAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockAIAnalyzer) Analyze(ctx context.Context, imageData []byte) (*entity.AnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, imageData)
	ret0, _ := ret[0].(*entity.AnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockAIAnalyzerMockRecorder) Analyze(ctx, imageData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockAIAnalyzer)(nil).Analyze), ctx, imageData)
}
