// Code generated by MockGen. DO NOT EDIT.
// Source: ./validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImageValidator is a mock of ImageValidator interface.
type MockImageValidator struct {
	ctrl     *gomock.Controller
	recorder *MockImageValidatorMockRecorder
}

// MockImageValidatorMockRecorder is the mock recorder for MockImageValidator.
type MockImageValidatorMockRecorder struct {
	mock *MockImageValidator
}

// NewMockImageValidator creates a new mock instance.
func NewMockImageValidator(ctrl *gomock.Controller) *MockImageValidator {
	mock := &MockImageValidator{ctrl: ctrl}
	mock.recorder = &MockImageValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageValidator) EXPECT() *MockImageValidatorMockRecorder {
	return m.recorder
}

// ValidateContent mocks base method.
func (m *MockImageValidator) ValidateContent(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContent", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContent indicates an expected call of ValidateContent.
func (mr *MockImageValidatorMockRecorder) ValidateContent(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContent", reflect.TypeOf((*MockImageValidator)(nil).ValidateContent), data)
}

// ValidateSize mocks base method.
func (m *MockImageValidator) ValidateSize(size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSize", size)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSize indicates an expected call of ValidateSize.
func (mr *MockImageValidatorMockRecorder) ValidateSize(size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSize", reflect.TypeOf((*MockImageValidator)(nil).ValidateSize), size)
}

// ValidateType mocks base method.
func (m *MockImageValidator) ValidateType(filename, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateType", filename, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateType indicates an expected call of ValidateType.
func (mr *MockImageValidatorMockRecorder) ValidateType(filename, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateType", reflect.TypeOf((*MockImageValidator)(nil).ValidateType), filename, contentType)
}
